- name: Install PHP Remi Repository
  dnf: name=https://rpms.remirepo.net/fedora/remi-release-30.rpm update_cache=yes state=latest
 
- name: Enable PHP Remi Repository
  command: dnf module reset php -y
  command: dnf module enable php:remi-7.4 -y

- name: Install PHP Extensions
  dnf: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"
